export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST';
export const BLOG_POST_LIST_RECEIVED = 'BLOG_POST_LIST_RECEIVED';
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR';
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD';

export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST';
export const BLOG_POST_RECEIVED = 'BLOG_POST_RECEIVED';
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR';
export const BLOG_POST_UNLOAD = 'BLOG_POST_UNLOAD';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_RECEIVED = 'COMMENT_LIST_RECEIVED';
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';
export const COMMENT_LIST_UNLOAD = 'COMMENT_LIST_UNLOAD';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SET_ID = 'USER_SET_ID';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
