export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST';
export const BLOG_POST_LIST_RECEIVED = 'BLOG_POST_LIST_RECEIVED';
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR';
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD';

export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST';
export const BLOG_POST_RECEIVED = 'BLOG_POST_RECEIVED';
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR';
export const BLOG_POST_UNLOAD = 'BLOG_POST_UNLOAD';

